# Generated by Django 2.2.1 on 2019-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='image',
            field=models.ImageField(default='', upload_to='stud_image'),
        ),
    ]
