# Generated by Django 2.2.1 on 2019-05-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0003_auto_20190511_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='image',
            field=models.ImageField(default='', upload_to='stud_image'),
        ),
    ]
