# Generated by Django 2.2.1 on 2019-05-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0005_student_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='register_model',
        ),
    ]
