# Generated by Django 2.2.1 on 2019-05-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0008_student_d_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Emp_detail',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.Emp')),
            ],
        ),
    ]
