# Generated by Django 2.2.1 on 2019-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0009_emp_emp_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
