# Generated by Django 2.2.1 on 2019-05-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0014_auto_20190511_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp_detail',
            new_name='Emp_d',
        ),
        migrations.RenameModel(
            old_name='Emp',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='emp_d',
            old_name='emp',
            new_name='employee',
        ),
    ]
